#!/usr/bin/env bash

for N in 501 1479
do
  ARGS=""
  ARGS="${ARGS} --geometry /data/Geometry/Scuff_geometry/AlN_cylinders.scuffgeo"
  ARGS="${ARGS} --OmegaFile OmegaFile"
  ARGS="${ARGS} --Power --ZForce"
  ARGS="${ARGS} --DSIRadius 5"
  ARGS="${ARGS} --DSIPoints 302"

  scuff-neq ${ARGS}
done
